"""Talking-avatar generation for CreatorOS Reels.

The generator uploads the existing CreatorOS narration to HeyGen and asks an
already configured avatar to lip-sync that exact audio. This keeps the existing
voice pipeline while making the presenter actually speak the generated script.
"""

from __future__ import annotations

import os
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import httpx


@dataclass
class AvatarResult:
    video_path: Path
    provider: str
    video_id: str


class AvatarGenerationError(RuntimeError):
    """Raised when a configured talking-avatar provider cannot generate video."""


class AvatarGenerator:
    """Generate a real lip-synced presenter video.

    Configuration:
      CREATOROS_AVATAR_PROVIDER=heygen
      CREATOROS_AVATAR_API_KEY=<secret>
      CREATOROS_AVATAR_ID=<HeyGen avatar look ID>

    HeyGen's v3 video API accepts an uploaded audio asset for lip-sync, so the
    same Edge-TTS narration already generated by CreatorOS is used by the avatar.
    """

    BASE_URL = "https://api.heygen.com"
    POLL_SECONDS = 5
    MAX_WAIT_SECONDS = 900

    def __init__(self, provider: Optional[str] = None):
        self.provider = (
            provider
            or os.getenv("CREATOROS_AVATAR_PROVIDER")
            or os.getenv("AVATAR_PROVIDER", "none")
        ).strip().lower()
        self.api_key = (
            os.getenv("CREATOROS_AVATAR_API_KEY")
            or os.getenv("AVATAR_API_KEY", "")
        ).strip()
        self.avatar_id = (
            os.getenv("CREATOROS_AVATAR_ID")
            or os.getenv("AVATAR_ID", "")
        ).strip()

    def generate(self, audio_path: str | Path, output_path: str | Path) -> AvatarResult:
        if self.provider in {"", "none", "disabled"}:
            raise AvatarGenerationError(
                "Talking avatar is disabled. Set CREATOROS_AVATAR_PROVIDER=heygen."
            )
        if self.provider != "heygen":
            raise AvatarGenerationError(f"Unsupported avatar provider: {self.provider}")
        if not self.api_key:
            raise AvatarGenerationError(
                "HeyGen is enabled but CREATOROS_AVATAR_API_KEY is missing."
            )
        if not self.avatar_id:
            raise AvatarGenerationError(
                "HeyGen is enabled but CREATOROS_AVATAR_ID is missing."
            )

        audio_path = Path(audio_path)
        output_path = Path(output_path)
        if not audio_path.exists() or audio_path.stat().st_size == 0:
            raise AvatarGenerationError(f"Narration audio does not exist: {audio_path}")
        output_path.parent.mkdir(parents=True, exist_ok=True)

        headers = {"x-api-key": self.api_key}
        print("[Avatar Generator] Uploading narration to HeyGen...", flush=True)
        with httpx.Client(timeout=60.0) as client:
            with audio_path.open("rb") as audio_file:
                response = client.post(
                    f"{self.BASE_URL}/v3/assets",
                    headers=headers,
                    files={"file": (audio_path.name, audio_file, "audio/mpeg")},
                )
            self._raise_for_api(response, "audio upload")
            asset_id = response.json().get("data", {}).get("asset_id")
            if not asset_id:
                raise AvatarGenerationError("HeyGen did not return an audio asset_id.")

            print(f"[Avatar Generator] Audio asset ready: {asset_id}", flush=True)
            print("[Avatar Generator] Creating lip-synced avatar video...", flush=True)
            response = client.post(
                f"{self.BASE_URL}/v3/videos",
                headers={**headers, "Content-Type": "application/json"},
                json={
                    "type": "avatar",
                    "avatar_id": self.avatar_id,
                    "audio_asset_id": asset_id,
                    "title": output_path.stem,
                    "resolution": "1080p",
                    "aspect_ratio": "9:16",
                    "output_format": "mp4",
                    "engine": {"type": "avatar_iv"},
                },
            )
            self._raise_for_api(response, "avatar video creation")
            video_id = response.json().get("data", {}).get("video_id")
            if not video_id:
                raise AvatarGenerationError("HeyGen did not return a video_id.")

            print(f"[Avatar Generator] HeyGen job: {video_id}", flush=True)
            deadline = time.monotonic() + self.MAX_WAIT_SECONDS
            while time.monotonic() < deadline:
                status_response = client.get(
                    f"{self.BASE_URL}/v3/videos/{video_id}",
                    headers=headers,
                )
                self._raise_for_api(status_response, "avatar status")
                data = status_response.json().get("data", {})
                status = str(data.get("status", "")).lower()
                print(f"[Avatar Generator] Status: {status}", flush=True)

                if status == "completed":
                    video_url = data.get("video_url")
                    if not video_url:
                        raise AvatarGenerationError(
                            "HeyGen marked the avatar video completed but returned no video_url."
                        )
                    self._download(client, video_url, output_path)
                    print(
                        f"[Avatar Generator] Talking avatar saved: {output_path} "
                        f"({output_path.stat().st_size} bytes)",
                        flush=True,
                    )
                    return AvatarResult(
                        video_path=output_path,
                        provider="heygen",
                        video_id=video_id,
                    )

                if status in {"failed", "error", "cancelled"}:
                    raise AvatarGenerationError(
                        f"HeyGen avatar generation failed: {data.get('failure_message') or data.get('error') or status}"
                    )
                time.sleep(self.POLL_SECONDS)

        raise AvatarGenerationError(
            f"HeyGen avatar generation timed out after {self.MAX_WAIT_SECONDS}s (video_id={video_id})."
        )

    @staticmethod
    def _raise_for_api(response: httpx.Response, operation: str) -> None:
        if response.is_success:
            return
        try:
            payload = response.json()
            detail = payload.get("error", {}).get("message") or str(payload)
        except Exception:
            detail = response.text[:500]
        raise AvatarGenerationError(
            f"HeyGen {operation} failed ({response.status_code}): {detail}"
        )

    @staticmethod
    def _download(client: httpx.Client, url: str, output_path: Path) -> None:
        with client.stream("GET", url, timeout=120.0) as response:
            if not response.is_success:
                raise AvatarGenerationError(
                    f"Unable to download completed HeyGen video ({response.status_code})."
                )
            with output_path.open("wb") as destination:
                for chunk in response.iter_bytes():
                    destination.write(chunk)
        if not output_path.exists() or output_path.stat().st_size == 0:
            raise AvatarGenerationError("HeyGen returned an empty avatar video.")
